-- MySQL Script generated by MySQL Workbench
-- Tue Jan 27 11:00:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Òptica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Òptica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Òptica` DEFAULT CHARACTER SET utf8 ;
USE `Òptica` ;

-- -----------------------------------------------------
-- Table `Òptica`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Òptica`.`Address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(100) NOT NULL,
  `street_number` VARCHAR(10) NOT NULL,
  `floor` VARCHAR(20) NULL,
  `door` VARCHAR(20) NULL,
  `city` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Òptica`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Òptica`.`Supplier` (
  `id_supplier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `numberPhone` VARCHAR(20) NOT NULL,
  `fax` VARCHAR(20) NOT NULL,
  `nif` VARCHAR(12) NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id_supplier`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  INDEX `fk_Suppliers_address_idx` (`address_id` ASC) VISIBLE,
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Suppliers_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `Òptica`.`Address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Òptica`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Òptica`.`Brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `Supplier_id` INT NOT NULL,
  PRIMARY KEY (`id_brand`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_brand_Suppliers1_idx` (`Supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_brand_Suppliers1`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `Òptica`.`Supplier` (`id_supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Òptica`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Òptica`.`Customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `postal_address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registration_date` DATE NOT NULL,
  `recommended_by` INT NULL,
  PRIMARY KEY (`id_customer`),
  INDEX `fk_Customers_Customers1_idx` (`recommended_by` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Customers1`
    FOREIGN KEY (`recommended_by`)
    REFERENCES `Òptica`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Òptica`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Òptica`.`Employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Òptica`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Òptica`.`Glasses` (
  `id_glasses` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `graduation_eye_L` DECIMAL(4,2) NOT NULL,
  `graduation_eye_R` DECIMAL(4,2) NOT NULL,
  `frame_type` ENUM('flotant', 'pasta', 'metalica') NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  `lens_color_R` VARCHAR(45) NOT NULL,
  `lens_color_L` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `Customer_id` INT NULL,
  `Employee_id` INT NULL,
  INDEX `fk_glasses_brand1_idx` (`brand_id` ASC) VISIBLE,
  PRIMARY KEY (`id_glasses`),
  INDEX `fk_Glasses_Customers1_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Glasses_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_glasses_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `Òptica`.`Brand` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Customers1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `Òptica`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `Òptica`.`Employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
