-- MySQL Script generated by MySQL Workbench
-- Tue Jan 27 13:07:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Province` (
  `idProvince` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvince`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Province_id` INT NOT NULL,
  PRIMARY KEY (`idCity`),
  INDEX `fk_City_Province_idx` (`Province_id` ASC) VISIBLE,
  CONSTRAINT `fk_City_Province`
    FOREIGN KEY (`Province_id`)
    REFERENCES `mydb`.`Province` (`idProvince`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  `Province_id` INT NOT NULL,
  `City_id` INT NOT NULL,
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_Customer_Province1_idx` (`Province_id` ASC) VISIBLE,
  INDEX `fk_Customer_City1_idx` (`City_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Province1`
    FOREIGN KEY (`Province_id`)
    REFERENCES `mydb`.`Province` (`idProvince`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_City1`
    FOREIGN KEY (`City_id`)
    REFERENCES `mydb`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Store` (
  `idStore` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `City_id` INT NOT NULL,
  `Province_id` INT NOT NULL,
  PRIMARY KEY (`idStore`),
  INDEX `fk_Store_City1_idx` (`City_id` ASC) VISIBLE,
  INDEX `fk_Store_Province1_idx` (`Province_id` ASC) VISIBLE,
  CONSTRAINT `fk_Store_City1`
    FOREIGN KEY (`City_id`)
    REFERENCES `mydb`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_Province1`
    FOREIGN KEY (`Province_id`)
    REFERENCES `mydb`.`Province` (`idProvince`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `order_type` ENUM('A domicili', 'Recollir en botiga') NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `Customer_id` INT NOT NULL,
  `Store_id` INT NOT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_Orders_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Orders_Store1_idx` (`Store_id` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Store1`
    FOREIGN KEY (`Store_id`)
    REFERENCES `mydb`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `Product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Image` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `type` ENUM('Pizza', 'Hamburguesa', 'Beguda') NOT NULL,
  PRIMARY KEY (`Product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza` (
  `Category_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  INDEX `fk_Pizza_Category1_idx` (`Category_id` ASC) VISIBLE,
  PRIMARY KEY (`Product_id`),
  CONSTRAINT `fk_Pizza_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `mydb`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_details` (
  `idOrder_details` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `Orders_idOrders` INT NOT NULL,
  `Product_Product_id` INT NOT NULL,
  PRIMARY KEY (`idOrder_details`, `Orders_idOrders`, `Product_Product_id`),
  INDEX `fk_Order_details_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  INDEX `fk_Order_details_Product1_idx` (`Product_Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_details_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `mydb`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_details_Product1`
    FOREIGN KEY (`Product_Product_id`)
    REFERENCES `mydb`.`Product` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `job_position` ENUM('Cuiner', 'Repartidor') NOT NULL,
  `Store_id` INT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `fk_Employee_Store1_idx` (`Store_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Store1`
    FOREIGN KEY (`Store_id`)
    REFERENCES `mydb`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_type_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_type_details` (
  `idOrder_type_details` INT NOT NULL AUTO_INCREMENT,
  `delivered_at` DATETIME NOT NULL,
  `Orders_id` INT NOT NULL,
  `Employee_id` INT NOT NULL,
  PRIMARY KEY (`idOrder_type_details`, `Orders_id`, `Employee_id`),
  INDEX `fk_Order_type_details_Orders1_idx` (`Orders_id` ASC) VISIBLE,
  INDEX `fk_Order_type_details_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_type_details_Orders1`
    FOREIGN KEY (`Orders_id`)
    REFERENCES `mydb`.`Orders` (`idOrders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_type_details_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `mydb`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
