-- MySQL Script generated by MySQL Workbench
-- Wed Jan 28 11:56:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Youtube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Youtube` DEFAULT CHARACTER SET utf8 ;
USE `Youtube` ;

-- -----------------------------------------------------
-- Table `Youtube`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `birth_date` DATE NOT NULL,
  `gender` ENUM('Male', 'Female') NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  `postal_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Video` (
  `idVideo` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `file_size` DOUBLE NOT NULL,
  `file_name` VARCHAR(70) NOT NULL,
  `duration` TIME NOT NULL,
  `likes` INT NOT NULL,
  `dislikes` INT NOT NULL,
  `thumbnail` TEXT NOT NULL,
  `view_count` INT NOT NULL,
  `status` ENUM('Public', 'Private', 'Hidden') NOT NULL,
  `User_id` INT NOT NULL,
  `published_at` DATETIME NOT NULL,
  PRIMARY KEY (`idVideo`),
  INDEX `fk_Video_User_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Video_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `Youtube`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Video_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Video_tag` (
  `Video_id` INT NOT NULL,
  `Tag_id` INT NOT NULL,
  PRIMARY KEY (`Video_id`, `Tag_id`),
  INDEX `fk_Video_has_Tag_Tag1_idx` (`Tag_id` ASC) VISIBLE,
  INDEX `fk_Video_has_Tag_Video1_idx` (`Video_id` ASC) VISIBLE,
  CONSTRAINT `fk_Video_has_Tag_Video1`
    FOREIGN KEY (`Video_id`)
    REFERENCES `Youtube`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Video_has_Tag_Tag1`
    FOREIGN KEY (`Tag_id`)
    REFERENCES `Youtube`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Channel` (
  `idChannel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`idChannel`),
  INDEX `fk_Channel_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Channel_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Youtube`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Subscription` (
  `User_id` INT NOT NULL,
  `Channel_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Channel_id`),
  INDEX `fk_User_has_Channel_Channel1_idx` (`Channel_id` ASC) VISIBLE,
  INDEX `fk_User_has_Channel_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Channel_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Youtube`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Channel_Channel1`
    FOREIGN KEY (`Channel_id`)
    REFERENCES `Youtube`.`Channel` (`idChannel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Video_Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Video_Like` (
  `type` ENUM('Like', 'Dislike') NOT NULL,
  `created_at` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  `Video_id` INT NOT NULL,
  INDEX `fk_Video_Like_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Video_Like_Video1_idx` (`Video_id` ASC) VISIBLE,
  PRIMARY KEY (`User_id`, `Video_id`),
  CONSTRAINT `fk_Video_Like_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Youtube`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Video_Like_Video1`
    FOREIGN KEY (`Video_id`)
    REFERENCES `Youtube`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Playlist` (
  `idPlaylist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `status` ENUM('Public', 'Private') NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`idPlaylist`),
  INDEX `fk_Playlist_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Playlist_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Youtube`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Playlist_Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Playlist_Video` (
  `Playlist_id` INT NOT NULL,
  `Video_id` INT NOT NULL,
  PRIMARY KEY (`Playlist_id`, `Video_id`),
  INDEX `fk_Playlist_has_Video_Video1_idx` (`Video_id` ASC) VISIBLE,
  INDEX `fk_Playlist_has_Video_Playlist1_idx` (`Playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_Playlist_has_Video_Playlist1`
    FOREIGN KEY (`Playlist_id`)
    REFERENCES `Youtube`.`Playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Playlist_has_Video_Video1`
    FOREIGN KEY (`Video_id`)
    REFERENCES `Youtube`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `comment_text` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  `Video_id` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  INDEX `fk_Comment_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Comment_Video1_idx` (`Video_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Youtube`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Video1`
    FOREIGN KEY (`Video_id`)
    REFERENCES `Youtube`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`Comment_Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`Comment_Like` (
  `type` ENUM('Like', 'Dislike') NOT NULL,
  `created_at` DATETIME NOT NULL,
  `User_id` INT NOT NULL,
  `Comment_id` INT NOT NULL,
  INDEX `fk_Comment_Like_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Comment_Like_Comment1_idx` (`Comment_id` ASC) VISIBLE,
  PRIMARY KEY (`User_id`, `Comment_id`),
  CONSTRAINT `fk_Comment_Like_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `Youtube`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Like_Comment1`
    FOREIGN KEY (`Comment_id`)
    REFERENCES `Youtube`.`Comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
